name: Notify Google of sitemap update

on:
  page_build

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Ping Google
    steps:
      - name: Send HTTP GET request to Google as ping
        run: wget http://www.google.com/ping?sitemap=https://mobilit.snic.nl/sitemap.xml

